### ISSUE TITLE
Create Connect Four Game

### ISSUE THREAD

**Issue by omareq** [omareq/omareq.github.io#10]
# Create Connect Four Game

## Overview

Generate a Connect 4 game with Artificial Intelligence.

## Todo

- [ ] Draw the connect four board
- [ ] Implement mouse clicks to add new pieces
- [ ] Create an AI algorithm 
- [ ] UI to show optimal move for each player
- [ ] UI slider to select ability of the AI from perfect to random, 
- [ ] UI to select AI gameplay for each player
- [ ] UI to set a time limit for AI to think

## Inspiration

[Christian Kollmann Connect Four AI Game](https://www.ist.tugraz.at/oaich/)

![image](https://user-images.githubusercontent.com/16267873/226129495-f1db869d-85ad-4722-857f-b6fa310161bd.png)
