### ISSUE TITLE
Create Hangman Game

### ISSUE THREAD

**Issue by omareq** [omareq/omareq.github.io#12]
# Create a Hangman Game
## Overview

Create a classic hangman game online

## Todo

- [x] Generate a random word
- [x] Draw blank letter locations
- [x] Add game mechanics
- [ ] Add UI to select the length of the word as some sort of difficulty

## Inspiration

![image](https://user-images.githubusercontent.com/16267873/226131198-a72bb29a-9a3c-4011-88f4-8f1d9fdf3071.png)

**Comment by omareq** [comment]
commit 2a0b6b1 and previous branch addresses items 1 to 3
