### ISSUE TITLE
Implicit Iterative Integration 

### ISSUE THREAD

**Issue by omareq** [omareq/omareq.github.io#13]
# Implicit Iterative Integration 
## Overview 
Use this implicit iterative integration to find the solution of a time-dependent ordinary differential equation.

## Todo

- [ ] Implement forward Euler method
- [ ] Implement backward Euler method
- [ ] Implement forward-backward Euler method
- [ ] UI to select different types of functions eg: periodic, polynomial, exponential, random signal
- [ ] Options to add noise to functions 

## Inspiration

![image](https://user-images.githubusercontent.com/16267873/226133922-0d693e8e-405a-4467-9d06-d222feace48a.png)
