### ISSUE TITLE
Interpolation Methods

### ISSUE THREAD

**Issue by omareq** [omareq/omareq.github.io#14]
# Interpolation Methods
## Overview
Implement different interpolation schemes and show what the differences are.

## Todo

- [ ] Linear interpolation
- [ ] Cosine interpolation
- [ ] Cubic Interpolation
- [ ] Hermite polynomial
- [ ] UI to select interpolation methods
- [ ] UI to show multiple interpolation methods on the same graph
- [ ] UI to change points to set functions or user-selected points

## Inspiration

[Paul Bourke Interpolation Examples](http://paulbourke.net/miscellaneous/interpolation/)

![image](https://user-images.githubusercontent.com/16267873/226134529-3ec36bbc-4d38-477d-ac1d-7d56cafe5e1e.png)
