### ISSUE TITLE
Create Ising Model

### ISSUE THREAD

**Issue by omareq** [omareq/omareq.github.io#15]
# Create Ising Model
## Overview
Create a script that implements the Ising model.  This can be used to show phase transitions.

## Todo

- [ ] Create Ising model
- [ ] Plot magnetization
- [ ] Plot heat capacity
- [ ] UI For variable model parameters: temperature, lattice size 

## Inspiration

[B.D. Hammel](https://www.bdhammel.com/ising-model/)

![image](https://user-images.githubusercontent.com/16267873/226137736-8ad973a2-54be-4ca0-b825-f53a9211b9ea.png)
