### ISSUE TITLE
 Create Checkers Game

### ISSUE THREAD

**Issue by omareq** [omareq/omareq.github.io#8]
# Create Checkers Game

## Overview
Create a checkers game with an AI to test my understanding of the Minimax algorithm.  This should also implement Alpha Beta pruning.

## To-Do List
- [ ] Draw the checkers board
- [ ] Implement mouse clicks to move pieces
- [ ] Highlight Possible move locations
- [ ] Block disallowed moves eg not capturing a piece
- [ ] Create Minimax
- [ ] Implement Alpha Beta Pruning

## Inspiration 
Tech with Tim
https://www.youtube.com/watch?v=RjdrFHEgV2o 

![image](https://user-images.githubusercontent.com/16267873/217653443-2f645ee2-5f86-450b-aa84-f473392379d8.png)
